name: template-golang
services:
  webapi:
    env_file:
      - path: ./env/example.env
        required: true
      - path: ./env/.env
        required: false
    ports:
      - "${WEBAPI_PORT:-8080}:${WEBAPI_PORT:-8080}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:${WEBAPI_PORT:-8080}/build-version",
        ]
      start_period: 5s
      interval: 1s
      timeout: 1s
      retries: 5
